### ISSUE TITLE
Add support for more license_expression fields

### ISSUE THREAD

**Issue by tdruez** [nexB/aboutcode-toolkit#563]
In particular `declared_license_expression` and `other_license_expression` following their addition in DejaCode.

**Comment by DennisClark** [comment]
thanks for logging this issue @tdruez    we definitely want support for the two new license fields in aboutcode-toolkit.

**Comment by chinyeungli** [comment]
Questions:
1. Do the `declared_license_expression` and `other_license_expression` also use the Scancode license key/expression, or can they be in other formats, such as a list or a string like 'MIT' (which is invalid, as it should be mit)?
2. When I do the `--fetch_license`, should these licenses also be fetched and created?

**Comment by mjherzog** [comment]
These should be standard license expressions with either ScanCode or SPDX license ids (one or the other per expression - no mix & match). We will, of course, have other license names and "expressions" in Scan data, but not in ABCTK.

**Comment by chinyeungli** [comment]
Another question, for the generated ABOUT file, should the new licenses also "group" into the "licenses"?
Current format
```
about_resource: test.c
name: test.c
license_expression: mit
declared_license_expression: isc
other_license_expression: mit-0
copyright: robot
licenses:
  - key: mit
    name: MIT License
    file: mit.LICENSE
    url: https://scancode-licensedb.aboutcode.org/mit.LICENSE
    spdx_license_key: MIT
```

Should it be something like:
```
about_resource: test.c
name: test.c
license_expression: mit
declared_license_expression: isc
other_license_expression: mit-0
copyright: robot
licenses:
  - key: mit
    name: MIT License
    file: mit.LICENSE
    url: https://scancode-licensedb.aboutcode.org/mit.LICENSE
    spdx_license_key: MIT
  - key: isc
    name: ISC License
    file: isc.LICENSE
    url: https://scancode-licensedb.aboutcode.org/isc.LICENSE
    spdx_license_key: ISC
  - key: mit-0
    name: MIT-0-Clause
    file: mit-0.LICENSE
    url: https://scancode-licensedb.aboutcode.org/mit-0.LICENSE
    spdx_license_key: MIT-0
```
